config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :symptoms, except: :show
  resources :medicines
  get 'home/index'

  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "admin" or user.role == 1 or user.role == :admin or user.role == 'admin'
        can :read, :all
      else
        can :manage, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  has_many :medicine_symptoms, dependent: :destroy
  has_many :symptoms, through: :medicine_symptoms

  belongs_to :user
  
  has_one_attached :picture
end

app/models/medicine_symptom.rb
class MedicineSymptom < ApplicationRecord
  belongs_to :medicine
  belongs_to :symptom
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  has_many :medicine_symptoms, dependent: :destroy
  has_many :medicines, through: :medicine_symptoms

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :symptoms, dependent: :destroy
  has_many :medicines, dependent: :destroy

  enum role: { guest: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    # Para mostrar uma mensagem de alerta descomente as linhas abaixo
    flash[:notice] = exception.message
    redirect_to root_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  # load_and_authorize_resource
  
  def index
    if current_user.role != "admin"
      @medicine = Medicine.where(user_id: current_user.id)
      @symptom = Symptom.where(user_id: current_user.id)
    else
      @medicine = Medicine.all
      @symptom = Symptom.all
    end
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: %i[ show edit update destroy ]

  load_and_authorize_resource

  # GET /medicines or /medicines.json
  def index
    if current_user.role == 'admin'
      @q = Medicine.ransack(params[:q])
      @medicines = @q.result
    else
      @q = Medicine.where(user_id: current_user.id).ransack(params[:q])
      @medicines = @q.result
    end   
  end

  # GET /medicines/1 or /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new(user_id: current_user.id)
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines or /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: "Remédio salvo com sucesso." }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1 or /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: "Remédio atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1 or /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: "Remédio excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medicine_params
      params.require(:medicine).permit(:picture, :name, :quantity, :medicine_validity, :medicine_insert, :used_to, :purchase_date, :user_id, symptom_ids: [])
    end
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  before_action :set_symptom, only: %i[ edit update destroy ]

  load_and_authorize_resource
  
  # GET /symptoms or /symptoms.json
  def index
    if current_user.role == 'admin'
      @symptoms = Symptom.all
    else
      @symptoms = Symptom.where(user_id: current_user.id)
    end
  end

  # GET /symptoms/new
  def new
    @symptom = Symptom.new(user_id: current_user.id)
  end

  # GET /symptoms/1/edit
  def edit
  end

  # POST /symptoms or /symptoms.json
  def create
    @symptom = Symptom.new(symptom_params)

    respond_to do |format|
      if @symptom.save
        format.html { redirect_to({ action: :index}, {notice: "Sintoma foi cadastrado com sucesso."}) }
        format.json { render :index, status: :created, location: @symptom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /symptoms/1 or /symptoms/1.json
  def update
    respond_to do |format|
      if @symptom.update(symptom_params)
        format.html { redirect_to({ action: :index}, {notice: "Sintoma foi atualizado com sucesso."}) }
        format.json { render :index, status: :ok, location: @symptom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /symptoms/1 or /symptoms/1.json
  def destroy
    @symptom.destroy
    respond_to do |format|
      format.html { redirect_to symptoms_url, notice: "Sintoma foi excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_symptom
      @symptom = Symptom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def symptom_params
      params.require(:symptom).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden %>
    <%= f.input :name, label: "Nome" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Salvar categoria", class: "btn btn-success btn-margin-bottom" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <h1 class="bd-highlight">Categorias</h1>
  <%= link_to 'Voltar', root_path, class: "m-3 bd-highlight" %>
</div>

<% if @categories.any? %>
  <table class="table table-striped table-edit">
    <thead>
      <tr>
        <th>Nome</th>
        <% if current_user.role == 'admin' %>
          <th>Usuário</th>
        <% end %>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <% if current_user.role == 'admin' %>
            <td>
              <%= category.user.name %>
            </td>
          <% end %>
          <td>
            <%= link_to edit_category_path(category) do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </td>
          <td>
            <%= link_to category, method: :delete, data: { confirm: 'Tem certeza?' } do %>
              <i class="fas fa-times-circle red"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  Não há categoria cadastrada
<% end %>

<br>

<%= link_to new_category_path, class: "btn btn-success btn-margin-bottom" do %>
  Nova Categoria
<% end %>

app/views/home/index.html.erb
<h1>PharmMy</h1>

<% if @medicine.last == nil and @symptom.last == nil %>
  <p>
    Seja bem vindo a PharmMy. Sua farmacinha particular e online!
    No momento você não tem nada cadastrado no sistema.

    <p>Para começar a usar a PharmMy comece cadastrando um sintoma <%= link_to "aqui", new_symptom_path %></p>
  </p>
<% else %>  
  <p>Lista de remédios que tenho em casa | Atualizado em:
    <span class="badge bg-dark">
      <%= @medicine.last ? @medicine.last.updated_at.strftime("%d/%m/%Y") : "---" %>
    </span> 
  </p>

  <br />

  <div class="row btn-margin-bottom">
    <div class="col-4">
      <%= link_to medicines_path, class: "btn btn-primary" do %>
        Remédios cadastrados
        <span class="badge bg-secondary">
          <%= @medicine.count %>
        </span>
      <% end %>
    </div>
    <div class="col-4">
      <%= link_to symptoms_path, class: "btn btn-info" do %>
        Sintomas cadastrados
        <span class="badge bg-secondary">
          <%= @symptom.count %>
        </span>
      <% end %>
    </div>
    <div class="col-4">
      <button type="button" class="btn btn-warning pe-none">
         Próximo ao vencimento
         <span class="badge bg-secondary">
          0
         </span>
      </button>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PharmMy | Elton Santos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>

      <% unless flash.empty? %>
        <script type="text/javascript">
          <% flash.each do |f| %>
              <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
              toastr['<%= type %>']('<%= f[1] %>', '', {
                "closeButton": true,
                "positionClass": "toast-top-right", 
                "onclick": null, 
                "showDuration": "300", 
                "hideDuration": "1000", 
                "timeOut": "5000", 
                "extendedTimeOut": "1000", 
                "showEasing": "swing", 
                "hideEasing": "linear", 
                "showMethod": "fadeIn", 
                "progressBar": true,
                "hideMethod": "fadeOut" });
          <% end %>
        </script>
      <% end %>

      <div class="app">
        <div class="main-wrapper">
          <section class="section pb-0 bg-gradient-info">
            <nav class="navbar navbar-expand-lg navbar-dark bg-gradient-info">
              <div class="container justify-content-center mt-5">
                <%= image_tag("logo.svg")%>
              </div>
            </nav>
            <main class="container card shadow shadow-lg--hover mt-3">
              <div class="btn-margin-top">
                <%=link_to destroy_user_session_path, method: :delete, class: "float-end btn-sign-out" do %>
                  Bem vindo <%= current_user.name %>,
                  <i class="fas fa-sign-out-alt"></i>
                  Sair
                <% end %>
              </div>
              <%= yield %>
            </main>
          </section>
        </div>
      </div>
    <% else %>
      <%= yield %>  
    <% end %>
  </body>
</html>

app/views/medicines/_form.html.erb
<%= simple_form_for(@medicine) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.file_field :picture %>
    <%= f.input :user_id, as: :hidden %>
    <%= f.input :name, label: "Nome" %>
    <%= f.input :quantity, label: "Quantidade" %>
    <%= f.input :purchase_date, label: "Comprado em" %>  
    <%= f.input :medicine_insert, label: "Bula" %>
    <%= f.input :used_to, label: "Usado para"%>
    <%= f.input :medicine_validity, label: "Validade", input_html: { class: "datepicker" }  %>
    <%= f.association :symptoms, as: :check_boxes, collection: Symptom.where(user_id: current_user.id), label: "Sintomas", wrapper: :vertical_collection_inline %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Cadastrar remédio", class: "btn btn-success btn-margin-bottom" %>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <h1 class="bd-highlight">Editar remédio</h1>
  <%= link_to 'Voltar', medicines_path, class: "m-3 bd-highlight" %>
</div>

<%= render 'form', medicine: @medicine %>

app/views/medicines/index.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <h1 class="bd-highlight">Remédios</h1>
  <%= link_to 'Voltar', root_path, class: "m-3 bd-highlight" %>
</div>

<h5>Buscar por remédio</h5>
<%= search_form_for @q, html: { class: 'row row-cols-lg-auto g-3 align-items-center search-form' } do |f| %>
  <div class="col-12">
    <%= f.input :name_cont, label: false, placeholder: 'Nome', class: 'form-control' %>
  </div>
  <div class="col-12">
    <%= f.input :symptoms_medicine_symptoms_symptom_name_cont, label: false, placeholder: 'Sintoma', class: 'form-control' %>
  </div>
  <div class="col-12">
    <%= f.button :button, name: '', class: 'btn-warning btn-align' do %>
      <i class="fas fa-search"></i>
      Buscar
    <% end %>
  </div>
<% end %>

<br />

<% if @medicines.any? %>
  <table class="table table-striped table-edit">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Quantidade</th>     
        <th>Data de compra</th>
        <th>Validade</th>
        <th>Sintoma</th>
        <% if current_user.role == 'admin' %>
          <th>Usuário</th>
        <% end %>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @medicines.each do |medicine| %>
        <tr>
          <td><%= medicine.name %></td>
          <td><%= medicine.quantity %></td>
          <td>
            <i class="fas fa-shopping-basket green"></i>
            <%= medicine.purchase_date.strftime("%d/%m/%Y") %>
          </td>
          <td>
            <i class="fa fa-tag green"></i>
            <%= medicine.medicine_validity.strftime("%d/%m/%Y") %>
          </td>
          <td>
            <% medicine.symptoms.each do |c| %>
              <span class="badge bg-info">
                <%= c.name %>
              </span>
            <% end %>
          </td>
          <% if current_user.role == 'admin' %>
            <td>
              <%= medicine.user.name %>
            </td>
          <% end %>
          <td>
            <%= link_to medicine do %>
              <i class="fas fa-search"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_medicine_path(medicine) do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </td>
          <td>
            <%= link_to medicine, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-times-circle red"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  Não há remédio cadastrado.
<% end %>
<br>

<%= link_to new_medicine_path, class: "btn btn-success btn-margin-bottom" do %>
  Novo Remédio
<% end %>

app/views/medicines/new.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <h1 class="bd-highlight">Novo remédio</h1>
  <%= link_to 'Voltar', medicines_path, class: "m-3 bd-highlight" %>
</div>

<%= render 'form', medicine: @medicine %>

app/views/medicines/show.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <h1 class="bd-highlight">Detalhes do remédio</h1>
  <%= link_to 'Voltar', medicines_path, class: "m-3 bd-highlight" %>
</div>

<p>
  <strong>Foto:</strong>
  <% if @medicine.picture.attached? %>
    <%= image_tag @medicine.picture %>
  <% end %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @medicine.name %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @medicine.quantity %>
</p>

<p>
  <strong>Validade:</strong>
  <%= @medicine.medicine_validity.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Bula:</strong>
  <%= @medicine.medicine_insert %>
</p>

<p>
  <strong>Usei para:</strong>
  <%= @medicine.used_to %>
</p>

<p>
  <strong>Data de compra:</strong>
  <%= @medicine.purchase_date.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Sintomas:</strong>
  <% @medicine.symptoms.each do |c| %>
    <span class="badge bg-info">
      <%= c.name %>
    </span>
  <% end %>
</p>

<% if can? :manage, @medicine %>
  <%= link_to edit_medicine_path(@medicine), class: "btn btn-warning btn-margin-bottom" do %>
    Editar
  <% end %>
<% end %>

app/views/symptoms/_form.html.erb
<%= simple_form_for(@symptom) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden %>
    <%= f.input :name, label: "Nome" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Cadastrar sintoma", class: "btn btn-success btn-margin-bottom" %>
  </div>
<% end %>

app/views/symptoms/edit.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <h1 class="bd-highlight">Editar Sintoma</h1>
  <%= link_to 'Voltar', symptoms_path, class: "m-3 bd-highlight" %>
</div>

<%= render 'form', symptom: @symptom %>

app/views/symptoms/index.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <h1 class="bd-highlight">Sintomas</h1>
  <%= link_to 'Voltar', root_path, class: "m-3 bd-highlight" %>
</div>

<% if @symptoms.any? %>
  <table class="table table-striped table-edit">
    <thead>
      <tr>
        <th>Nome</th>
        <% if current_user.role == 'admin' %>
          <th>Usuário</th>
        <% end %>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @symptoms.each do |symptom| %>
        <tr>
          <td><%= symptom.name %></td>
          <% if current_user.role == 'admin' %>
            <td>
              <%= symptom.user.name %>
            </td>
          <% end %>
          <td>
            <%= link_to edit_symptom_path(symptom) do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </td>
          <td>
            <%= link_to symptom, method: :delete, data: { confirm: 'Tem certeza?' } do %>
              <i class="fas fa-times-circle red"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  Não há sintoma cadastrado
<% end %>

<br>

<%= link_to new_symptom_path, class: "btn btn-success btn-margin-bottom" do %>
  Nova sintoma
<% end %>

app/views/symptoms/new.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <h1 class="bd-highlight">Novo sintoma</h1>
  <%= link_to 'Voltar', symptoms_path, class: "m-3 bd-highlight" %>
</div>

<%= render 'form', symptom: @symptom %>